name: Python Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: http://localhost:3000

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    # Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Install JSON Server
    - name: Install JSON Server
      run: npm install -g json-server

    # Start Mock API
    - name: Start Mock API
      run: |
        json-server students.json --port 3000 &
        sleep 5

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Install Chrome
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    # Run API , UI Tests & GENERATE ALLURE REPORTS
    - name: Run Tests with Allure
      run: pytest -m "api or ui" --alluredir=allure-results

    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        npm install -g allure-commandline

    - name: Generate Allure HTML Report
      run: allure generate allure-results -o allure-report --clean

    - name: Upload Allure HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report